---
title: ML4MI
listing:
  type: default
  sort-ui: false
  sort:
    - "date desc"
  image-height: 150px
  categories: true
  fields: [image, author, title, description, date, categories]
  date-format: "YYYY-MM-DD"
  page-size: 6
  contents:
    - "./**/*.qmd"
    - "!./**/index.qmd"

toc: false
toc-location: body
page-layout: full
title-block-banner: false
---
Explore a library of recordings (**netID required**) from the [Machine Learning for Medical Imaging (ML4MI)](https://ml4mi.wisc.edu/learning-opportunities/) community! Additional ML4MI talks can also be found on the UW-Madison [Kaltura Mediaspace](https://mediaspace.wisc.edu/channel/Machine%2BLearning%2Bfor%2BMedical%2BImaging%2B%2528ML4MI%2529%2BSeminar%2BSeries/355339002).

From the [ML4MI](https://ml4mi.wisc.edu/learning-opportunities/) webpage:

> A regular seminar series began in February 2018, and includes 1) seminars describing technical developments in ML with potential biomedical applications, 2) seminars by local or external Radiology researchers, describing problems that may benefit from ML approaches and ongoing projects involving ML techniques, and 3) seminars by biomedical researchers (not in Radiology), describing pioneering experiences applying ML in their fields of study. The seminar location will alternate between ECB/WID and SMPH/WIMR. These seminars will also provide an opportunity for UW researchers to become familiar with researchers “on the other side of campus.” 
