project:
  type: website
  resources: 
    - images/*

website:
  title: "Nexus: Crowdsourced ML Resources"
  page-navigation: true
  
  repo-url: https://github.com/UW-Madison-DataScience/ML-X-Nexus
  repo-actions: [edit]

  sidebar:
    tools:
      - icon: github
        href: https://github.com/UW-Madison-DataScience/ML-X-Nexus
        text: "GitHub organization"
    # logo: "images/ML+X_Logo_Secondary_Tagline_Transparent.png"
    logo: "images/ML+X_Logo_Secondary_Transparent.png"

    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home

      - href: Learn/Guides/How-to-contribute.qmd
        text: "How to contribute?" 

      - text: "Learn"
        href: Learn/index.qmd 
        contents:
          - text: "Books"
            href: Learn/Books/index.qmd
          - text: "Guides"
            href: Learn/Guides/index.qmd
          - text: "Workshops"
            href: Learn/Workshops/index.qmd
          - text: "Videos"
            href: Learn/Videos/index.qmd

      - text: "Toolbox"
        href: Toolbox/index.qmd
        contents:
          - text: "Compute"
            href: Toolbox/Compute/index.qmd
          - text: "Data"
            href: Toolbox/Data/index.qmd
          - text: "Models"
            href: Toolbox/Models/index.qmd
            
      - text: "Applications"
        href: Applications/index.qmd
        contents:
          - text: "Blogs"
            href: Applications/Blogs/index.qmd
          - text: "EDA"
            href: Applications/EDA-examples/index.qmd 
          - text: "Videos"
            href: Applications/Videos/index.qmd
            contents:
            - text: "Forums"
              href: Applications/Videos/Forums/index.qmd
            - text: "ML4MI"
              href: Applications/Videos/ML4MI/index.qmd
            - text: "SILO"
              href: Applications/Videos/SILO/index.qmd
            - text: "Other"
              href: Applications/Videos/Other/index.qmd

      - href: glossary.qmd
        text: "Category glossary"

format:
  html:
    theme:
      light: [cosmo, fonts.scss, theme.scss]
      dark: [cosmo, fonts.scss, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

language:
  repo-action-links-edit: "Improve this page"

