project:
  type: website
  resources: 
    - images/*

website:
  title: "Nexus: Crowdsourced ML Resources"
  page-navigation: true
  
  repo-url: https://github.com/UW-Madison-DataScience/ML-X-Nexus
  repo-actions: [edit]

  sidebar:
    tools:
      - icon: github
        href: https://github.com/UW-Madison-DataScience/ML-X-Nexus
        text: "GitHub organization"
    logo: "images/ML+X_Logo_Secondary_Transparent.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home

      - href: Resources/Guides/How-to-contribute.qmd
        text: "How to contribute?" 

      - text: "Resources"
        href: Resources/index.qmd 
        contents:
          - text: "Books"
            href: Resources/Books/index.qmd
          - text: "EDA"
            href: Resources/EDA-examples/index.qmd 
          - text: "Guides"
            href: Resources/Guides/index.qmd
          - text: "Workshops"
            href: Resources/Workshops/index.qmd
          - text: "Videos"
            href: Resources/Videos/index.qmd

      - text: "Applications"
        href: Local-events/Forums/index.qmd
        contents:
          - text: "Forums"
            href: Local-events/Forums/index.qmd
          - text: "Blogs"
            href: Resources/Blogs/index.qmd


      # - href: pretrained-models.qmd
        # text: "Pretrained models"
      - href: glossary.qmd
        text: "Glossary of ML terms"

format:
  html:
    theme:
      light: [cosmo, fonts.scss, theme.scss]
      dark: [cosmo, fonts.scss, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

language:
  repo-action-links-edit: "Improve this page"

