---
title: SILO
listing:
  type: default
  sort-ui: false
  sort:
    - "date desc"
  image-height: 150px
  categories: true
  fields: [image, author, title, description, date, categories]
  date-format: long
  page-size: 6
  contents:
    - "./**/*.qmd"
    - "!./**/index.qmd"

toc: false
toc-location: body
page-layout: full
title-block-banner: false
---
The [Systems, Information, Learning and Optimization (SILO)](https://silo.wisc.edu/) research group at the University of Wisconsin-Madison hosts a weekly seminar that covers a variety of topics related to machine learning, optimization, and information theory. SILO breaks down the research “silos” created by academic department boundaries by providing time and space for researchers to present their work, interact, and find common threads.

A non exhaustive list of recorded SILO seminars (feel free to add others!) can be found here on Nexus. Visit the [SILO - Past Talks](https://silo.wisc.edu/past-talks/) page to explore additional talks of interest.

### Join the next live SILO!
* **Where**: Orchard View Room (rm. 3280), [Discovery Building](https://www.map.wisc.edu/?initObj=0212) & via Zoom. 
* **When**: Check the [SILO schedule](https://silo.wisc.edu/upcoming-talks/) and join the [Google group](https://groups.google.com/a/g-groups.wisc.edu/g/silo/) to receive a calendar invite (with Zoom link) and other updates. 
