---
title: "Title of Resource" # enter the title of the resource (typically the name of the article/workshop/video/book/etc. )
author: "External" # leave as is
date-modified: "last-modified" # leave as is
date-format: long # leave as is

# Enter a list of relevant categories/tags for this resource, including the type (workshop, book, video, podcast, etc.) and subject of focus, e.g., ...
categories: 
  - Deep Learning
  - PyTorch
  - Workshop
  - External # You must use this tag for external resources
---

## About this external resource
<!-- MARKDOWN COMMENT: Replace the instructions below with URL -->
External link: [Insert the URL that will be displayed on Nexus — please remove "https:" from the URL](Insert the actual URL here)

<!-- MARKDOWN COMMENT: Replace the instructions below with your resource description -->
Brief description of the resource. Explain what the resource covers and its relevance. Mention any specific features, strengths, or weaknesses. This section should help potential users understand the value of the resource and what they can expect to learn or achieve by using it. 
#### Prerequisite resources
<!-- MARKDOWN COMMENT: If any prerequisite knowledge is required (e.g., Intro ML, Python, Intro Deep Learning), please also mention this — preferably by linking to existing materials on Nexus, e.g., ...
-->
- [Prerequisite Resource 1](Link to related Nexus resource 1)
- [Prerequisite Resource 2](Link to related Nexus resource 2)

### See also
<!-- MARKDOWN COMMENT: Please list any related resources below that might also be helpful (e.g., related books/videos, blog posts commenting on the resource, alternative approaches/frameworks, etc.) -->
- [Related Resource 1](Link to related resource 1): Brief description of related resource 1.
- [Related Resource 2](Link to related resource 2): Brief description of related resource 2.
- [Related Resource 3](Link to related resource 3): Brief description of related resource 3.

<!-- THIS IS A MARKDOWN COMMENT: Insert the URL for your resource below so that the resource can be previewed on the Nexus platform -->
```{=html}
<iframe width="1000" height="500" src="Insert URL for iframe here" title="Optional: Webpage example"></iframe>
