---
title: Exploring Artificial Intelligence @ UW-Madison
listing:
  type: default
  sort-ui: false
  sort:
    - "date desc"
  image-height: 150px
  categories: true
  fields: [image, author, title, description, date, categories]
  date-format: "YYYY-MM-DD"
  page-size: 6
  contents:
    - "./**/*.qmd"
    - "!./**/index.qmd"

toc: false
toc-location: body
page-layout: full
title-block-banner: false
---
Explore a library of recordings (**netID required**) from the *Exploring Artificial Intelligence @ UW-Madison* series! Additional talks can also be found on the [seminar website](https://it.wisc.edu/exploring-artificial-intelligence-uw-madison/).

From their website:

> In today’s rapidly evolving world, the importance of AI in our academic environment cannot be overstated. As technological advancements continue to shape our society, we believe it is crucial to explore the opportunities and challenges AI brings to the forefront of higher education.
> 
> This webinar series aimed to provide a platform for experts and visionaries in the field of AI to share their insights, research and experiences in the classroom, research lab and wider academic community. By delving into topics such as AI ethics, cutting-edge machine learning algorithms, automation and human-machine collaboration, we hoped to foster a deeper understanding of AI’s transformative potential and its implications for higher education.

