---
title: Intro to Deep Learning with Keras (Carpentries)
author: "Carpentries"
date-modified: "last-modified"
date-format: long
categories:
  - Deep learning
  - Keras
  - Workshop
  - Carpentries
---

## About this external resource

**External link**: [carpentries-incubator.github.io/deep-learning-intro/](https://carpentries-incubator.github.io/deep-learning-intro/)

The Carpentries is a global organization of researchers who volunteer their time and effort to create workshops that teach software engineering and data analysis skills to other researchers. UW-Madison has its own [local Carpentries community](https://datascience.wisc.edu/uw-madison-carpentries-community/) which is actively engaged in developing new ML/AI workshops. 

The above workshop from the Carpentries will walk you through introductory deep learning concepts as well as how to build a neural networks in Keras. Keras is high-level wrapper framework (uses PyTorch or Tensorflow in the backend) which allows you to train and evaluate neural networks in just a few lines of code. It may take slightly longer to train a Keras model (compared to PyTorch and Tensorflow), but the difference in performance is often negligible for those that only need to train a few models. The ability to quickly build and test models is the primary selling point of Keras.

### See also
- [**Workshop**: Intro to Deep Learning with PyTorch](https://uw-madison-datascience.github.io/ML-X-Nexus/Guides/Deep-learning_PyTorch/index.html): Explore PyTorch as an alternative deep learning framework.
- [**Book**: Understanding Deep Learning - Simon J.D. Prince](https://udlbook.github.io/udlbook/): This free textbook is a good modern overview of deep learning, and provides colab notebooks to explore deep learning concepts and implementations. The book uses PyTorch as its framework of choice. You may find additional details in this book that the workshop only briefly touches on.

## Resource preview
```{=html}
<iframe width="1000" height="500" src="https://carpentries-incubator.github.io/deep-learning-intro/" title="Webpage example"></iframe>
```
