---
title: Intro to PyTorch
author: "External"
date-modified: "last-modified"
date-format: long
categories:
  - Deep learning
  - PyTorch
  - Workshop
  - External
---

## About this external resource

**External link**: [www.udacity.com/course/deep-learning-pytorch--ud188](https://www.udacity.com/course/deep-learning-pytorch--ud188)

Udacity offers many free educational materials focused on tech-related topics. The below workshop from Udacity will walk you through introductory deep learning concepts as well as how to build a neural networks in PyTorch. PyTorch is one of the most popular deep learning frameworks. Known for its speed and more "pythonic" feel, it is frequently the go-to choice for most researchers. The biggest downside of PyTorch, compared to a framework like Keras, is that it is quite verbose. You'll need to right a couple hundred lines of code to train and evaluate your neural network model. Keras is a great alternative for those who are just getting started with neural networks, as you can train/evaluate in just a dozen or so lines of code.


#### See also
- [Intro to Deep Learning with Keras](https://carpentries-incubator.github.io/deep-learning-intro/): Explore Keras as an alternative deep learning framework
- [*Understanding Deep Learning* - Simon J.D. Prince](https://udlbook.github.io/udlbook/): This free textbook is a good modern overview of deep learning, and provides colab notebooks to explore deep learning concepts and implementations. The book uses PyTorch as its framework of choice. You may find additional details in this book that the workshop only briefly touches on.

```{=html}
<iframe width="1000" height="500" src="https://www.udacity.com/enrollment/ud188" title="Webpage example"></iframe>
```

