on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn scikit-learn scipy statsmodels jupyter nbformat missingno


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run the save_insights.py script
      - name: Save GitHub Insights
        env:
          REPO_NAME: ${{ github.repository }}
          TOKEN: ${{ secrets.GH_PAT }}
        run: python insights/save_insights.py

      # Commit and Push Insights
      - name: Commit and Push Insights
        run: |
          git config --local user.email "endemann@wisc.edu"
          git config --local user.name "qualiaMachine"
          git add insights/
          git commit -m "Save GitHub insights on publish"
          git push