name: Convert QMD to IPYNB and Commit

on:
  push:
    paths:
      - 'Learn/Notebooks/**/*.qmd'
      - '.github/workflows/qmd-to-ipynb.yml'
      - '.scripts/format_notebook_metadata.py'
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Convert all .qmd notebooks to .ipynb (no execution)
        run: |
          shopt -s globstar nullglob
          for file in Learn/Notebooks/**/*.qmd; do
            [[ "$(basename "$file")" == "index.qmd" ]] && continue
            echo "Converting $file"
            quarto convert "$file" -o "${file%.qmd}.ipynb"
          done

      - name: Install dependencies  for formatting notebook
        run: pip install nbformat pyyaml

      - name: Format notebook metadata (strip YAML + inject header cell)
        run: python3 .scripts/format_notebook_metadata.py

      - name: Commit and push .ipynb files
        run: |
          git config user.name "quarto-bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          find Learn/Notebooks -name "*.ipynb" -exec git add {} +
          git commit -m "Auto-convert .qmd notebooks to .ipynb [skip ci]" || echo "No changes to commit"
          git push
