name: Convert QMD to IPYNB and Commit

on:
  push:
    paths:
      - 'Learn/Notebooks/**/*.qmd'
      - '.github/workflows/qmd-to-ipynb.yml'
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Convert all .qmd notebooks to .ipynb (no execution)
        run: |
          for file in Learn/Notebooks/**/*.qmd; do
            [ -f "$file" ] || continue
            quarto convert "$file" --to ipynb --output "${file%.qmd}.ipynb"
          done

      - name: Remove YAML frontmatter from notebooks
        run: |
          python3 <<EOF
import nbformat, glob
for path in glob.glob('Learn/Notebooks/**/*.ipynb', recursive=True):
    with open(path, 'r', encoding='utf-8') as f:
        nb = nbformat.read(f, as_version=4)
    if nb.cells and nb.cells[0].cell_type == 'markdown' and nb.cells[0].source.strip().startswith('---'):
        nb.cells.pop(0)
        with open(path, 'w', encoding='utf-8') as f:
            nbformat.write(nb, f)
EOF

      - name: Commit and push .ipynb files
        run: |
          git config user.name "quarto-bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Learn/Notebooks/**/*.ipynb
          git commit -m "Auto-convert .qmd notebooks to .ipynb [skip ci]" || echo "No changes to commit"
          git push
