# -------------------------------------------------------------------------------------
# GitHub Actions Workflow: Save GitHub Insights (Scheduled)
# -------------------------------------------------------------------------------------
# This workflow does the following:
# 1. Runs a script to save GitHub repository insights (e.g., contributors, commit data)
# 2. Commits and pushes any changes made by the script
#
# It runs on:
# - A weekly schedule (every Monday at 04:00 UTC)
# - Manual runs from the GitHub UI (workflow_dispatch)
# -------------------------------------------------------------------------------------


# .github/workflows/save-insights.yml
on:
  schedule:
    - cron: '0 4 * * 1'  # Every Monday at 04:00 UTC
  workflow_dispatch:

name: Save GitHub Insights

jobs:
  save-insights:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn scikit-learn \
                      scipy statsmodels jupyter nbformat missingno

      - name: Run Insights Script
        env:
          REPO_NAME: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python insights/save_insights.py

      - name: Check for Changes
        id: changes
        run: |
          if [ -d "insights" ]; then
            git add insights/
            if git diff --cached --quiet; then
              echo "changed=false" >> $GITHUB_ENV
            else
              echo "changed=true" >> $GITHUB_ENV
            fi
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Insights
        if: env.changed == 'true'
        run: |
          git config --local user.email "endemann@wisc.edu"
          git config --local user.name "qualiaMachine"
          git commit -m "Save GitHub insights (scheduled)"
          git push
